# Generated by Django 4.2.7 on 2023-11-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzadetails',
            name='order',
        ),
        migrations.RemoveField(
            model_name='pizzadetails',
            name='pizza_number',
        ),
        migrations.AddField(
            model_name='pizzadetails',
            name='toppings',
            field=models.ManyToManyField(to='core.toppings'),
        ),
    ]
