# Generated by Django 4.2.7 on 2023-11-20 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cheesetype_price_pizzabase_price_toppings_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza_details',
        ),
        migrations.AddField(
            model_name='pizzadetails',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='core.pizzaorder'),
        ),
    ]
