# Generated by Django 4.2.7 on 2023-11-21 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_pizzaorder_pizza_details_pizzadetails_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderstatus',
            old_name='order',
            new_name='order_id',
        ),
    ]
